### ISSUE TITLE
some question about the code

### ISSUE THREAD

**Issue by xujinwei13** [pyannote/pyannote-db-voxceleb#1]
Hello! I am a student and interested in speaker identification. Recently, I read your paper "VoxCeleb: a large-scale speaker identification dataset" and I think your work is perfect. I want to follow your works, but the result is unsatisfactory. Could you share your source code to me? If yes, I would appreciate it. I am sorry to bother you.

**Comment by hbredin** [comment]
I am not the author of the VoxCeleb paper. See http://www.robots.ox.ac.uk/~vgg/data/voxceleb/
