### ISSUE TITLE
duplicates.txt does not exist

### ISSUE THREAD

**Issue by guanjian729** [pyannote/pyannote-db-voxceleb#2]
hello,I want to download the voxceleb dataset at url in your scripts / readme: http: //www.robots.ox.ac.uk/~vgg/data/voxceleb, but I did not find duplicates.txt where is the download address?  so when  i run prepare_data.ipynb ,have an error:FileNotFoundError: File b'data/duplicates.txt' does not exist。what should i do?  very thanks.

**Comment by hbredin** [comment]
Not sure why you want to rerun `prepare_data.ipynb`...
Anyway, `duplicates.txt` can be downloaded from VoxCeleb website:
```
29/9/2017 VoxCeleb 1.1: After deduping the dataset, we have found a small list of repeated videos (34 videos). The list of duplicates can be found here. Note that these videos are only in the training set for identification, the test set remains unchanged.
```

**Comment by guanjian729** [comment]
OK,very thanks.
