### ISSUE TITLE
Question about annotation

### ISSUE THREAD

**Issue by royaljain** [pyannote/pyannote-db-voxceleb#3]
Hi,

Can you kindly tell how you created the annotations ? Specifically the timing of speech segments. Were they manually annotated ? Cause I can't find this info in voxceleb dataset

**Comment by hbredin** [comment]
I got it from http://www.robots.ox.ac.uk/~vgg/data/voxceleb/voxceleb1.zip linked on VoxCeleb [webpage](http://www.robots.ox.ac.uk/~vgg/data/voxceleb/).
