### ISSUE TITLE
! about voxceleb folder structure when run "pyannote-speaker-embedding train"

### ISSUE THREAD

**Issue by TTTJJJWWW** [pyannote/pyannote-db-voxceleb#7]
Hi! @hbredin 
when i run "pyannote-speaker-embedding train", i set the dir_path to voxceleb, but i doubts about folder structure of voxceleb.
can your give me a example to show the folder structure of voxceleb?

**Comment by hbredin** [comment]
I have just updated the README with [detailed instructions](https://github.com/pyannote/pyannote-db-voxceleb#installation).
Please re-open this issue if needed.
