### ISSUE TITLE
voxceleb tiemstamp file

### ISSUE THREAD

**Issue by wosecz** [pyannote/pyannote-db-voxceleb#8]
Does anybody know the meaning of the third to fifth rows of the timestamp files?
![image](https://user-images.githubusercontent.com/10692992/69956050-21195a80-1553-11ea-8a56-af389fcbcf54.png)

**Comment by hbredin** [comment]
Please contact the authors of VoxCeleb directly:
http://www.robots.ox.ac.uk/~vgg/data/voxceleb/
